---
kubeStateMetrics:
  enabled: true

kube-state-metrics:
  fullnameOverride: kube-state-metrics
  selfMonitor:
    enabled: true
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node

nodeExporter:
  enabled: true

kubelet:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance

# extraScrapeConfigs: |
#   extraScrapeConfigs:
#     - job_name: 'kubelet'
#       kubernetes_sd_configs:
#         - role: node
#       metrics_path: /metrics/cadvisor
#       scheme: https
#       tls_config:
#         ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#         insecure_skip_verify: true
#       bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

# prometheus.yml:
#   scrape_configs:
#   - job_name: 'kube-state-metrics'
#     kubernetes_sd_configs:
#     - role: endpoints
#     relabel_configs:
#     - source_labels: [__meta_kubernetes_service_name]
#       regex: kube-state-metrics
#       action: keep
#     - action: labelmap
#       regex: __meta_kubernetes_service_label_(.+)
#     - source_labels: [__meta_kubernetes_namespace]
#       action: replace
#       target_label: kubernetes_namespace
#     - source_labels: [__meta_kubernetes_service_name]
#       action: replace